### ISSUE TITLE
Invalid KiCad footprints

### ISSUE THREAD

**Issue by ext-marko-marjanovic** [4ms/4ms-kicad-lib#1]
I tried to import KiCad footprints (directly, bypassing your installation manual) and found that the following three were marked as invalid by KiCad:
- Pin_Header_Straight_1x03.kicad_mod 
- Slide_Switch_SPDT_Nexsun_MS2201L6.kicad_mod 
- Slide_Switch_SS22D06-G6-H_Runrun.kicad_mod

Using KiCad 4.0.7 on Win10

**Comment by danngreen** [comment]
Sorry, I didn’t note in the docs that the footprints and symbols require Kicad 5 or newer. 
I believe what those three footprints have in common are custom pad shapes, which Kicad 4 does not support.
